version: "3.4"
services:
  postgres:
    image: mdillon/postgis:9.6-alpine
    environment:
      POSTGRES_DB: postgres
    # ports:
    #   - "5432:5432"
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgres/data
volumes:
  data: